name: Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install flake8
        run: pip install flake8

      - name: Run pytest
        run: pytest

      - name: Run flake8
        run: flake8 test_ml.py train_model.py ml/model.py main.py local_api.py
